[package]
name = "msh"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "msh"
path = "main.rs"

[dependencies]
nix      = { version = "0.27", features = ["process", "signal", "fs", "term"] }
libc     = "0.2"
tokio    = { version = "1", features = ["full"] }
reqwest  = { version = "0.12", features = ["json"] }
serde    = { version = "1", features = ["derive"] }
serde_json = "1"
rustyline  = "14"
glob       = "0.3"

[profile.release]
opt-level = 3
lto = false
